@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Asociación
class Conferencia
class Evento
class Localización
class Miembro
class Miembro_de_la_junta_directiva
class Persona
class Reunion_de_la_junta_directiva

Conferencia                    --^  Evento
Reunion_de_la_junta_directiva  --^  Evento

Miembro                        --^  Persona
Miembro_de_la_junta_directiva  --^  Miembro

Asociación o--  Localización
Asociación o--  Evento
Asociación o--  Persona

Conferencia  --  Persona
Evento  --  Miembro
Evento  --  Localización
Miembro_de_la_junta_directiva --  Reunion_de_la_junta_directiva

@enduml